package bean;
// Generated 06/10/2025 20:15:00 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * EgClientes generated by hbm2java
 */
@Entity
@Table(name="eg_clientes"
    ,catalog="db_erik_gimenes"
)
public class EgClientes  implements java.io.Serializable {


     private Integer idCliente;
     private String nome;
     private String email;
     private String sexo;
     private String telefone;
     private String endereco;
     private Date dataNasc;
     private String formaPagamento;
     private String rg;
     private String tipoCliente;
     private String cep;
     private String estado;
     private String cidade;
     private Date dataUltimaCompra;
     private String bairro;
     private Set<EgVenda> vendas = new HashSet<EgVenda>(0);
   

    public EgClientes() {
    }

    public EgClientes(String nome, String email, String sexo, String telefone, String endereco, Date dataNasc, String formaPagamento, String rg, String tipoCliente, String cep, String estado, String cidade, Date dataUltimaCompra, String bairro) {
       this.nome = nome;
       this.email = email;
       this.sexo = sexo;
       this.telefone = telefone;
       this.endereco = endereco;
       this.dataNasc = dataNasc;
       this.formaPagamento = formaPagamento;
       this.rg = rg;
       this.tipoCliente = tipoCliente;
       this.cep = cep;
       this.estado = estado;
       this.cidade = cidade;
       this.dataUltimaCompra = dataUltimaCompra;
       this.bairro = bairro;
    }
    public EgClientes(String nome, String email, String sexo, String telefone, String endereco, Date dataNasc, String formaPagamento, String rg, String tipoCliente, String cep, String estado, String cidade, Date dataUltimaCompra, String bairro, Set<EgVenda> vendas) {
       this.nome = nome;
       this.email = email;
       this.sexo = sexo;
       this.telefone = telefone;
       this.endereco = endereco;
       this.dataNasc = dataNasc;
       this.formaPagamento = formaPagamento;
       this.rg = rg;
       this.tipoCliente = tipoCliente;
       this.cep = cep;
       this.estado = estado;
       this.cidade = cidade;
       this.dataUltimaCompra = dataUltimaCompra;
       this.bairro = bairro;
       this.vendas = vendas;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id_cliente", unique=true, nullable=false)
    public Integer getIdCliente() {
        return this.idCliente;
    }
    
    public void setIdCliente(Integer idCliente) {
        this.idCliente = idCliente;
    }

    
    @Column(name="nome", length=150)
    public String getNome() {
        return this.nome;
    }
    
    public void setNome(String nome) {
        this.nome = nome;
    }

    
    @Column(name="email", length=150)
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }

    
    @Column(name="sexo", length=1)
    public String getSexo() {
        return this.sexo;
    }
    
    public void setSexo(String sexo) {
        this.sexo = sexo;
    }

    
    @Column(name="telefone", length=16)
    public String getTelefone() {
        return this.telefone;
    }
    
    public void setTelefone(String telefone) {
        this.telefone = telefone;
    }

    
    @Column(name="endereco", length=150)
    public String getEndereco() {
        return this.endereco;
    }
    
    public void setEndereco(String endereco) {
        this.endereco = endereco;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="data_nasc", length=10)
    public Date getDataNasc() {
        return this.dataNasc;
    }
    
    public void setDataNasc(Date dataNasc) {
        this.dataNasc = dataNasc;
    }

    
    @Column(name="forma_pagamento", length=150)
    public String getFormaPagamento() {
        return this.formaPagamento;
    }
    
    public void setFormaPagamento(String formaPagamento) {
        this.formaPagamento = formaPagamento;
    }

    
    @Column(name="rg", length=11)
    public String getRg() {
        return this.rg;
    }
    
    public void setRg(String rg) {
        this.rg = rg;
    }

    
    @Column(name="tipo_cliente", length=150)
    public String getTipoCliente() {
        return this.tipoCliente;
    }
    
    public void setTipoCliente(String tipoCliente) {
        this.tipoCliente = tipoCliente;
    }

    
    @Column(name="cep", length=9)
    public String getCep() {
        return this.cep;
    }
    
    public void setCep(String cep) {
        this.cep = cep;
    }

    
    @Column(name="estado", length=2)
    public String getEstado() {
        return this.estado;
    }
    
    public void setEstado(String estado) {
        this.estado = estado;
    }

    
    @Column(name="cidade", length=150)
    public String getCidade() {
        return this.cidade;
    }
    
    public void setCidade(String cidade) {
        this.cidade = cidade;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="data_ultima_compra", length=10)
    public Date getDataUltimaCompra() {
        return this.dataUltimaCompra;
    }
    
    public void setDataUltimaCompra(Date dataUltimaCompra) {
        this.dataUltimaCompra = dataUltimaCompra;
    }

    
    @Column(name="bairro", length=55)
    public String getBairro() {
        return this.bairro;
    }
    
    public void setBairro(String bairro) {
        this.bairro = bairro;
    }

    @OneToMany(fetch=FetchType.LAZY, mappedBy="egClientes")
    public Set<EgVenda> getVendas() {
        return this.vendas;
    }
    
    public void setVendas(Set<EgVenda> vendas) {
        this.vendas = vendas;
    }




}



