package bean;
// Generated 06/10/2025 20:15:00 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * EgProdutos generated by hbm2java
 */
@Entity
@Table(name="eg_produtos"
    ,catalog="db_erik_gimenes"
)
public class EgProdutos  implements java.io.Serializable {


     private Integer idProduto;
     private String nome;
     private String descricao;
     private double preco;
     private Date dataCadastro;
     private String marca;
     private String categoria;
     private Set<EgVendaProdutos> vendaProdutos = new HashSet<EgVendaProdutos>(0);

    public EgProdutos() {
    }

    public EgProdutos(String nome, String descricao, double preco, Date dataCadastro, String marca, String categoria) {
       this.nome = nome;
       this.descricao = descricao;
       this.preco = preco;
       this.dataCadastro = dataCadastro;
       this.marca = marca;
       this.categoria = categoria;
    }
    public EgProdutos(String nome, String descricao, double preco, Date dataCadastro, String marca, String categoria, Set<EgVendaProdutos> vendaProdutos) {
       this.nome = nome;
       this.descricao = descricao;
       this.preco = preco;
       this.dataCadastro = dataCadastro;
       this.marca = marca;
       this.categoria = categoria;
       this.vendaProdutos = vendaProdutos;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id_produto", unique=true, nullable=false)
    public Integer getIdProduto() {
        return this.idProduto;
    }
    
    public void setIdProduto(Integer idProduto) {
        this.idProduto = idProduto;
    }

    
    @Column(name="nome", length=150)
    public String getNome() {
        return this.nome;
    }
    
    public void setNome(String nome) {
        this.nome = nome;
    }

    
    @Column(name="descricao", length=200)
    public String getDescricao() {
        return this.descricao;
    }
    
    public void setDescricao(String descricao) {
        this.descricao = descricao;
    }

    
    @Column(name="preco", precision=9)
    public double getPreco() {
        return this.preco;
    }
    
    public void setPreco(double preco) {
        this.preco = preco;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="data_cadastro", length=10)
    public Date getDataCadastro() {
        return this.dataCadastro;
    }
    
    public void setDataCadastro(Date dataCadastro) {
        this.dataCadastro = dataCadastro;
    }

    
    @Column(name="marca", length=100)
    public String getMarca() {
        return this.marca;
    }
    
    public void setMarca(String marca) {
        this.marca = marca;
    }

    
    @Column(name="categoria", length=100)
    public String getCategoria() {
        return this.categoria;
    }
    
    public void setCategoria(String categoria) {
        this.categoria = categoria;
    }

    @OneToMany(fetch=FetchType.LAZY, mappedBy="egProdutos")
    public Set<EgVendaProdutos> getVendaProdutos() {
        return this.vendaProdutos;
    }
    
    public void setVendaProdutos(Set<EgVendaProdutos> vendaProdutos) {
        this.vendaProdutos = vendaProdutos;
    }




}

