package bean;
// Generated 06/10/2025 20:15:00 by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * EgUsuarios generated by hbm2java
 */
@Entity
@Table(name="eg_usuarios"
    ,catalog="db_erik_gimenes"
)
public class EgUsuarios  implements java.io.Serializable {


     private Integer idUsuario;
     private String nomeCompleto;
     private String apelido;
     private String cpf;
     private Date dataNascimento;
     private String senha;
     private String ativo;
     private int nivelAcesso;

    public EgUsuarios() {
    }

    public EgUsuarios(String nomeCompleto, String apelido, String cpf, Date dataNascimento, String senha, String ativo, int nivelAcesso) {
       this.nomeCompleto = nomeCompleto;
       this.apelido = apelido;
       this.cpf = cpf;
       this.dataNascimento = dataNascimento;
       this.senha = senha;
       this.ativo = ativo;
       this.nivelAcesso = nivelAcesso;
    }
   
    @Id @GeneratedValue(strategy=IDENTITY)
    @Column(name="id_usuario", unique=true, nullable=false)
    public Integer getIdUsuario() {
        return this.idUsuario;
    }
    
    public void setIdUsuario(Integer idUsuario) {
        this.idUsuario = idUsuario;
    }

    
    @Column(name="nome_completo", length=150)
    public String getNomeCompleto() {
        return this.nomeCompleto;
    }
    
    public void setNomeCompleto(String nomeCompleto) {
        this.nomeCompleto = nomeCompleto;
    }

    
    @Column(name="apelido", length=150)
    public String getApelido() {
        return this.apelido;
    }
    
    public void setApelido(String apelido) {
        this.apelido = apelido;
    }

    
    @Column(name="cpf", length=20)
    public String getCpf() {
        return this.cpf;
    }
    
    public void setCpf(String cpf) {
        this.cpf = cpf;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="data_nascimento", length=10)
    public Date getDataNascimento() {
        return this.dataNascimento;
    }
    
    public void setDataNascimento(Date dataNascimento) {
        this.dataNascimento = dataNascimento;
    }

    
    @Column(name="senha", length=50)
    public String getSenha() {
        return this.senha;
    }
    
    public void setSenha(String senha) {
        this.senha = senha;
    }

    
    @Column(name="ativo", length=1)
    public String getAtivo() {
        return this.ativo;
    }
    
    public void setAtivo(String ativo) {
        this.ativo = ativo;
    }

    
    @Column(name="nivel_acesso")
    public int getNivelAcesso() {
        return this.nivelAcesso;
    }
    
    public void setNivelAcesso(int nivelAcesso) {
        this.nivelAcesso = nivelAcesso;
    }




}

