package bean;
// Generated 06/10/2025 20:15:00 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * EgVendedor generated by hbm2java
 */
@Entity
@Table(name="eg_vendedor"
    ,catalog="db_erik_gimenes"
)
public class EgVendedor  implements java.io.Serializable {


     private Integer idVendedor;
     private String nomeCompleto;
     private String email;
     private String telefone;
     private Date dataCadastro;
     private double salario;
     private String endereco;
     private Set<EgVenda> vendas = new HashSet<EgVenda>(0);

    public EgVendedor() {
    }

    public EgVendedor(String nomeCompleto, String email, String telefone, Date dataCadastro, double salario, String endereco) {
       this.nomeCompleto = nomeCompleto;
       this.email = email;
       this.telefone = telefone;
       this.dataCadastro = dataCadastro;
       this.salario = salario;
       this.endereco = endereco;
    }
    
    public EgVendedor(String nomeCompleto, String email, String telefone, Date dataCadastro, double salario, String endereco, Set<EgVenda> vendas) {
       this.nomeCompleto = nomeCompleto;
       this.email = email;
       this.telefone = telefone;
       this.dataCadastro = dataCadastro;
       this.salario = salario;
       this.endereco = endereco;
       this.vendas = vendas;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id_vendedor", unique=true, nullable=false)
    public Integer getIdVendedor() {
        return this.idVendedor;
    }
    
    public void setIdVendedor(Integer idVendedor) {
        this.idVendedor = idVendedor;
    }

    
    @Column(name="nome_completo", length=150)
    public String getNomeCompleto() {
        return this.nomeCompleto;
    }
    
    public void setNomeCompleto(String nomeCompleto) {
        this.nomeCompleto = nomeCompleto;
    }

    
    @Column(name="email", length=150)
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }

    
    @Column(name="telefone", length=16)
    public String getTelefone() {
        return this.telefone;
    }
    
    public void setTelefone(String telefone) {
        this.telefone = telefone;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="data_cadastro", length=10)
    public Date getDataCadastro() {
        return this.dataCadastro;
    }
    
    public void setDataCadastro(Date dataCadastro) {
        this.dataCadastro = dataCadastro;
    }

    
    @Column(name="salario", precision=9)
    public double getSalario() {
        return this.salario;
    }
    
    public void setSalario(double salario) {
        this.salario = salario;
    }

    
    @Column(name="endereco", length=150)
    public String getEndereco() {
        return this.endereco;
    }
    
    public void setEndereco(String endereco) {
        this.endereco = endereco;
    }

    @OneToMany(fetch=FetchType.LAZY, mappedBy="egVendedor")
    public Set<EgVenda> getVendas() {
        return this.vendas;
    }
    
    public void setVendas(Set<EgVenda> vendas) {
        this.vendas = vendas;
    }




}

