package bean;
// Generated 06/10/2025 20:15:00 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * EgVendaProdutos generated by hbm2java
 */
@Entity
@Table(name="eg_vendas_produtos"
    ,catalog="db_erik_gimenes"
)
public class EgVendaProdutos  implements java.io.Serializable {


     private Integer idVendaProduto;
     private EgProdutos egProdutos;
     private EgVenda egVenda;
     private int quantidade;
     private double valorUnitario;
     private double valorTotal;

    public EgVendaProdutos() {
    }

    public EgVendaProdutos(EgProdutos egProdutos, EgVenda egVenda, int quantidade, double valorUnitario, double valorTotal) {
       this.egProdutos = egProdutos;
       this.egVenda = egVenda;
       this.quantidade = quantidade;
       this.valorUnitario = valorUnitario;
       this.valorTotal = valorTotal;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id_venda_produto", unique=true, nullable=false)
    public Integer getIdVendaProduto() {
        return this.idVendaProduto;
    }
    
    public void setIdVendaProduto(Integer idVendaProduto) {
        this.idVendaProduto = idVendaProduto;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="fk_produto")
    public EgProdutos getEgProdutos() {
        return this.egProdutos;
    }
    
    public void setEgProdutos(EgProdutos egProdutos) {
        this.egProdutos = egProdutos;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="fk_venda")
    public EgVenda getEgVenda() {
        return this.egVenda;
    }
    
    public void setEgVenda(EgVenda egVenda) {
        this.egVenda = egVenda;
    }

    
    @Column(name="quantidade")
    public int getQuantidade() {
        return this.quantidade;
    }
    
    public void setQuantidade(int quantidade) {
        this.quantidade = quantidade;
    }

    
    @Column(name="valor_unitario", precision=8)
    public double getValorUnitario() {
        return this.valorUnitario;
    }
    
    public void setValorUnitario(double valorUnitario) {
        this.valorUnitario = valorUnitario;
    }

    @Column(name="valor_total", precision=8)
    public double getValorTotal() {
        return this.valorTotal;
    }
    
    public void setValorTotal(double valorTotal) {
        this.valorTotal = valorTotal;
    }




}

