package bean;
// Generated 06/10/2025 20:15:00 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * EgVenda generated by hbm2java
 */
@Entity
@Table(name="eg_vendas"
    ,catalog="db_erik_gimenes"
)
public class EgVenda  implements java.io.Serializable {


     private Integer idVenda;
     private EgClientes egClientes;
     private EgVendedor egVendedor;
     private Date dataVenda;
     private double valorTotal;
     private Set<EgVendaProdutos> vendaProdutos = new HashSet<EgVendaProdutos>(0);

    public EgVenda() {
    }

    public EgVenda(EgClientes egClientes, EgVendedor egVendedor, Date dataVenda, double valorTotal) {
       this.egClientes = egClientes;
       this.egVendedor = egVendedor;
       this.dataVenda = dataVenda;
       this.valorTotal = valorTotal;
    }
    
    public EgVenda(EgClientes egClientes, EgVendedor egVendedor, Date dataVenda, double valorTotal, Set<EgVendaProdutos> vendaProdutos) {
       this.egClientes = egClientes;
       this.egVendedor = egVendedor;
       this.dataVenda = dataVenda;
       this.valorTotal = valorTotal;
       this.vendaProdutos = vendaProdutos;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id_venda", unique=true, nullable=false)
    public Integer getIdVenda() {
        return this.idVenda;
    }
    
    public void setIdVenda(Integer idVenda) {
        this.idVenda = idVenda;
    }

    @ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="fk_cliente")
    public EgClientes getEgClientes() {
        return this.egClientes;
    }
    
    public void setEgClientes(EgClientes egClientes) {
        this.egClientes = egClientes;
    }

    @ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="fk_vendedor")
    public EgVendedor getEgVendedor() {
        return this.egVendedor;
    }
    
    public void setEgVendedor(EgVendedor egVendedor) {
        this.egVendedor = egVendedor;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="data_venda", length=10)
    public Date getDataVenda() {
        return this.dataVenda;
    }
    
    public void setDataVenda(Date dataVenda) {
        this.dataVenda = dataVenda;
    }

    
    @Column(name="valor_total", precision=10)
    public double getValorTotal() {
        return this.valorTotal;
    }
    
   public void setValorTotal(double valorTotal) {
        this.valorTotal = valorTotal;
    }

    @OneToMany(fetch=FetchType.LAZY, mappedBy="egVenda")
    public Set<EgVendaProdutos> getVendaProdutos() {
        return this.vendaProdutos;
    }
    
    public void setVendaProdutos(Set<EgVendaProdutos> vendaProdutos) {
        this.vendaProdutos = vendaProdutos;
    }




}

